version: '2'
services:
  tensorflow:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./src:/tensorflow"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "./images:/tensorflow/images"
    environment:
      - DISPLAY=${DOCKER_IP}:0
    ports:
      - "8888:8888"
