version: '2'
services:
  tensorflow:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./src:/tensorflow"
    ports:
      - "8888:8888"
    environment:
      DISPLAY: ":0"