version: '2'
services:
  tensorflow:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - "./src:/tensorflow"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    ports:
      - "8888:8888"